version: ‘3’
services:
    web:
    restart: always
    build: .
    volumes:
        - ./:/var/www/

db:
    image: postgres:12.0-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: log_laravel
    volumes:
        - “./.docker/dbdata:/var/lib/postgresql/data”
